### ISSUE TITLE
Increasing precision 

### ISSUE THREAD

**Issue by kianfa** [MohammadAsadolahi/Reinforcement-learning-algorithm-Deep-Q-learning-for-cryptocurrency-trading#2]
I have checked your code and I noticed that you are using "close" prices of each candle while training tour DRL network. 
As far as I know using "Open Close High Low" of the candles would provide more information for training the system. Although, it increases the size of input layer, using these would probably increase the efficiency of the DRL agent. 

What other methods do you propose for increasing precision DRL agents which use Time Series as input data. 
I have chechked using mathematical features(feature engineering), pattern recognition, etc. But I do not know which one would be more effective. 

Please share your experience on this topic, and send me related papers if you know any. 

Thank You!

**Comment by MohammadAsadolahi** [comment]
Hi and thank you for asking.

I think the same general solutions would apply to this project as well. But you got to test them to see if they work or not. Honestly, until they are not tested no specific comment can be provided.

Best regards.

**Comment by kianfa** [comment]
Have you seen any paper talking about the best features for time series prediction?
